import os
import shutil
import yaml
import json
from datetime import datetime

# --- CONFIGURAÇÃO ---
MITRE_TACTICS = [
    'reconnaissance', 'resource_development', 'initial_access', 'execution',
    'persistence', 'privilege_escalation', 'defense_evasion', 'credential_access',
    'discovery', 'lateral_movement', 'collection', 'command_and_control',
    'exfiltration', 'impact'
]

def organizar(base):
    print("📦 Organizando regras...")
    # Protege arquivos essenciais
    protegidos = ['script.py', 'README.md', 'index.html', 'metrics.json', 'LICENSE']
    
    for f in os.listdir(base):
        if f in protegidos or f.startswith('.'): continue
        full = os.path.join(base, f)
        if not os.path.isfile(full): continue

        if f.endswith(('.yml', '.yaml')):
            tatica = 'execution'
            try:
                # Abrindo com UTF-8 para evitar erro na leitura também
                with open(full, 'r', encoding='utf-8') as stream:
                    data = yaml.safe_load(stream)
                    tags = data.get('tags', [])
                    for tag in tags:
                        for t in MITRE_TACTICS:
                            if t in tag.lower(): tatica = t
            except: pass
            
            dest = os.path.join(base, 'Sigma', tatica)
            os.makedirs(dest, exist_ok=True)
            shutil.move(full, os.path.join(dest, f))

def gerar(base):
    print("📊 Gerando métricas e README...")
    stats = {t: 0 for t in MITRE_TACTICS}
    tabela = ""
    total = 0

    for t in MITRE_TACTICS:
        pasta = os.path.join(base, 'Sigma', t)
        if os.path.exists(pasta):
            for f in os.listdir(pasta):
                if f.endswith(('.yml', '.yaml')):
                    total += 1
                    stats[t] += 1
                    tabela += f"| 🔴 | {t.upper()} | `{f}` | [Ver](./Sigma/{t}/{f}) |\n"

    metrics = {
        "updated_at": datetime.now().strftime("%d/%m/%Y %H:%M"),
        "total_rules": total,
        "sigma_syntax_errors": 0,
        "tactics": stats
    }
    
    # SALVANDO JSON COM UTF-8
    with open(os.path.join(base, 'metrics.json'), 'w', encoding='utf-8') as j:
        json.dump(metrics, j, indent=4, ensure_ascii=False)

    readme = f"""# 🛡️ Detection Engineering Portfolio
> Repositório automatizado de detecções Sigma e cobertura MITRE ATT&CK.

![Progress](https://img.shields.io/badge/PROGRESS-{min(int((total/14)*100), 100)}%25-blue)
![Sigma](https://img.shields.io/badge/Sigma-{total}-orange)
![Updated](https://img.shields.io/badge/Updated-{metrics['updated_at'].replace(' ', '_')}-green)

## 📊 Cobertura por Tática
| Tática | Quantidade |
| :--- | :---: |
"""
    for t, q in stats.items():
        if q > 0: readme += f"| {t.title()} | {q} |\n"
    
    readme += f"\n## 📋 Regras Ativas\n| Nível | Tática | Nome | Link |\n| :---: | :--- | :--- | :---: |\n{tabela}"
    readme += "\n\n---\n*Auto-generated by script.py*"

    # O PONTO CRÍTICO: SALVANDO README COM UTF-8
    with open(os.path.join(base, 'README.md'), 'w', encoding='utf-8') as f:
        f.write(readme)

def main():
    print("🚀 Enterprise Organizer")
    base = os.getcwd()
    organizar(base)
    gerar(base)
    print("✅ Sucesso! Agora pode fazer o commit e push.")

if __name__ == "__main__":
    main()